# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aoc2022',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/aoc2022',
                'lib_path': 'aoc2022'},
  'syms': {'aoc2022.core': {'aoc2022.core.foo': ('core.html#foo', 'aoc2022/core.py')}}}
